### ISSUE TITLE
UNKNOWN_ERROR & Invalid credentials errors

### ISSUE THREAD

**Issue by alasso** [deldrid1/node-red-contrib-firebase#27] opened 2019-02-07 16:58 UTC
Hi,

I am new to firebase and I want to connect my node-red app and I am received the errors UNKNOWN_ERROR and, in another node the error "Invalid credentials". 
I tryed with Anonymous and email/password authentication methods and always receive the same error.

Any help?

Thanks a lot in advance,
Adrian

**Comment by deldrid1** [comment] 2019-03-24 23:58
Duplicate of #16

**Closed as completed by deldrid1** 2019-03-24 23:58 UTC
