### ISSUE TITLE
Authentication for newbies

### ISSUE THREAD

**Issue by Vayatoalla** [deldrid1/node-red-contrib-firebase#29] opened 2019-03-24 23:21 UTC
After 2 days trying to authenticate the nodes in Firebase, I open this issue in the hope that someone will help me.
I have configurated an email account in Firebase but the nodes doesn't authenticate. Do not know if it is a problem with the account configuration in Firebase. 

Anyway, I think I could try the authentication with JWT, but do not have any idea of how to configure it. If someone could drop 3 or 4 lines with the basics it would be great!.

**Comment by deldrid1** [comment] 2019-03-24 23:57
Duplicate of #16 - closing

**Closed as completed by deldrid1** 2019-03-24 23:57 UTC
